server:
  port: 8081
spring:
  application:
    name: "pinguapp"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: false
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://admin:Riguja89@cluster0.ixo4j.mongodb.net/test?retryWrites=true&w=majority&appName=Cluster0"
  rabbitmq:
    host: "rabbitmq"
    username: "guest"
    password: "guest"
    virtual-host: "/"
    port: 5672
cors:
  allowed-origins: "*"